export { default as Home } from './Home'
export { default as About } from './About'
export { default as Register } from './Register'
export { default as NewStory } from './NewStory'
export { default as MyStory } from './MyStory'
export { default as Story } from './Story'